const ADD_PONEY = "ADD_PONEY";
const DELETE_PONEY = "DELETE_PONEY";
const UPDATE_PONEY = "UPDATE_PONEY";

const SET_LOADING = "SET_LOADING";
const SET_ERROR = "SET_ERROR";
const LOAD_PONEYS = "LOAD_PONEYS";
const TOGGLE_VIEW_DELETED_PONEYS = "TOGGLE_VIEW_DELETED_PONEYS";

const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";

export {
  ADD_PONEY,
  DELETE_PONEY,
  UPDATE_PONEY,
  SET_LOADING,
  SET_ERROR,
  LOAD_PONEYS,
  LOGIN,
  LOGOUT,
  TOGGLE_VIEW_DELETED_PONEYS
};
